# Generated by Django 5.1.3 on 2024-11-12 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='products/original/')),
                ('image_small', models.ImageField(blank=True, null=True, upload_to='products/small/')),
                ('image_medium', models.ImageField(blank=True, null=True, upload_to='products/medium/')),
                ('image_large', models.ImageField(blank=True, null=True, upload_to='products/large/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.subcategory')),
            ],
        ),
    ]
