# Generated by Django 5.1.3 on 2024-11-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Original image of the product.', upload_to='products/original/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_large',
            field=models.ImageField(blank=True, help_text='Large version of the product image.', null=True, upload_to='products/large/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_medium',
            field=models.ImageField(blank=True, help_text='Medium version of the product image.', null=True, upload_to='products/medium/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, help_text='Small version of the product image.', null=True, upload_to='products/small/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='The name of the product.', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(help_text='Unique slug for the product URL.', max_length=100, unique=True),
        ),
    ]
